### ISSUE TITLE
Prepare PR for net-use-malloc branch

### ISSUE THREAD

**Issue by rick-monster** [rick-monster/aleph#17]
memory management has been refactored, arbitrary op deletion/insertion works.  Try to separate this work out from the changes to operators, then pull-request the uncontroversial stuff...

**Comment by rick-monster** [comment]
also test the snot out of memory management & arbitrary op insertion/deletion!

**Comment by catfact** [comment]
heya - just to clarify something - in `net-use-malloc`, operators allocated using fixed-sized chunks from `bigOpPool` and `smallOpPool`, as outlined in [monome/#251](https://github.com/monome/aleph/issues/174)

is this solely to facilitate arbitrary op deletion? obviously it makes memory use less efficient than the old style of simply advancing the op pool pointer by the size of the last op. obviously arbitrary op deletion is an important function, so it's totally cool, but i wonder if there's some other consideration i've forgotten in the last few months..

**Comment by rick-monster** [comment]
yea - it's a scheme to avoid heap fragmentation.  I remember now heap compaction is basically impossible for certain of the ops, which register pointers to their allocated memory off with the OS functions.  So those portions of memory become unmoveable.

The bigOpPool/smallOpPool is my way of making the solution more *predictable*.  It's inspired by picolisp memory management - every object in picolisp is the same size so there's no problem of fragmentation.  Same idea for the op pools - if you give a smallOp chunk of memory back to the OS, it can always be reused for another smallOp, because they're all using the same memory chunk size.  Whereas if they all have different sizes, you can end up with fragmentation.

My judgement was that the small amount of wasted memory was not going to be a bottleneck for scene size/complexity - let's go back over those calculations...

**Comment by rick-monster** [comment]
256 smallOps & 16 bigOps are the limits I set:

https://github.com/rick-monster/aleph/blob/net-use-malloc/apps/bees/src/op_pool.h#L9-L13

That leaves tonnes of real estate for malloc/free to grab big chunks for huge ops which don't fit in 1k.  We can also malloc/free as a failover when big or small op pools get exhausted (maybe that's already implemented).

Here are the current upper limits on number of operators, inputs, outputs etc
https://github.com/monome/aleph/blob/dev/apps/bees/src/net.h#L19-L27

**Comment by rick-monster** [comment]
Just rebased net-use-malloc pretty hard onto monome/dev.  Uzi stress test commenced at 14:26 with the code from this branch:

https://github.com/rick-monster/aleph/tree/net-use-malloc-rebased

**Comment by rick-monster** [comment]
stress test ran for over an hour till I stopped it at 15:33. Definitely ready for a pull-request now...
